model:
  embed_dim: 3
  lossconfig:
    disc_start: 50001
    kl_weight: 0.000001
    disc_weight: 0.5
    disc_in_channels: 1
  ddconfig:
    double_z: True
    z_channels: 3
    resolution: [320, 320]
    in_channels: 1
    out_ch: 1
    ch: 128
    ch_mult: [ 1,2,4]  # num_down = len(ch_mult)-1
    num_res_blocks: 2
    attn_resolutions: [ ]
    dropout: 0.0
  ckpt_path: #'/home/zhuchenyang/project/hyx/data/pretrain_weights/model-kl-d4.ckpt'

data:
  name: edge
  img_folder: '/mnt/no1/miaochenlong/DiffusionEdge/data-image-out2/train'
  augment_horizontal_flip: True
  batch_size: 3

trainer:
  gradient_accumulate_every: 2
  lr: !!float 5e-6
  min_lr: !!float 5e-7
  train_num_steps: 400000
  save_and_sample_every: 10000
  log_freq: 10000
  results_folder: '/mnt/no1/miaochenlong/DiffusionEdge/results/testout2'
  amp: False
  fp16: False